cluster_name = google_dataproc_cluster.spark_cluster.cluster_name
region = google_dataproc_cluster.spark_cluster.region
endpoint = google_dataproc_cluster.spark_cluster.endpoint
master_instance_group = google_dataproc_cluster.spark_cluster.master_instance_group
worker_instance_group = google_dataproc_cluster.spark_cluster.worker_instance_group